# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PoopScoop' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PoopScoop
  
  pod 'GooglePlaces'
  pod 'GooglePlacePicker'
  pod 'GoogleMaps'

  target 'PoopScoopTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PoopScoopUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
